<?php
    include("phpconnect/connIdeaBase.php");
    include("template/head.html");
    include("pages/ideabase/IdeaBaseHead.php");
    include("template/nav.html");
    include("template/loginStatus.php");
    include("pages/ideabase/IdeaBaseBody.php");
    include("template/footer.html");
?>