<?php
    include("phpconnect/connItinerary.php");
    include("template/head.html");
    include("pages/itinerary/itineraryHead.php");
    include("template/nav.html");
    include("template/loginStatus.php");
    include("pages/itinerary/itineraryBody.php");
    include("template/footer.html");
?>