<?php
    include("phpconnect/connPreplanned.php");
    include("template/head.html");
    include("pages/activity/preplannedHead.php");
    include("template/nav.html");
    include("template/loginStatus.php");
    include("pages/activity/preplannedBody.php");
    include("template/footer.html");
?>