<?php
    include("phpconnect/ConnSavedItin.php");
    include("template/head.html");
    include("pages/saved-itinerary/saved-itinerary-head.php");
    include("template/nav.html");
    include("template/loginStatus.php");
    include("pages/saved-itinerary/saved-itinerary-body.php");
    include("template/footer.html");
?>